version: "3.8"
services:
  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
      target: development
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app
  db:
    container_name: db_dev
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app
  db-test:
    container_name: db-test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5431:5432
    volumes:
      - db-test-data:/var/lib/postgresql/data
volumes:
  db-data:
  db-test-data:
networks:
  app:
    driver: bridge
