version: "3.8"
services:
  nginx:
    container_name: nginx_prod
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
      target: production
    volumes:
      - /usr/src/app/node_modules
  frontend:
    container_name: frontend_prod
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
      target: production
  db:
    container_name: db_prod
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    command: >
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
volumes:
  db-data:
